devs_circle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    # Password Reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),


    path('update-profile/', user_views.profile_update, name='update-profile'),
    path('user_profile/', user_views.user_profile, name='user-profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path
from . import views
from .views import (QuestionCreateView, QuestionDetailView,
                    QuestionListView, QuestionUpdateView,
                    QuestionDeleteView, CommentUpdateView, CommentDeleteView,
                    UserQuestionListView)

app_name = 'quiz'

urlpatterns = [
    path('', QuestionListView.as_view(), name='devs-home'),
    path('home/', QuestionListView.as_view(), name='quiz-index'),
    path('user/<str:username>/', UserQuestionListView.as_view(), name='user-questions'),
    # path('<int:pk>/', QuestionDetailView.as_view(), name='question-detail'),
    path('create_new/', QuestionCreateView.as_view(), name='question-create'),
    path('<int:pk>/update/', QuestionUpdateView.as_view(), name='question-update'),
   # path('<int:pk>/comment/', CommentCreateView.as_view(),
    #     name='question-comment'),
    path('<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    # path('<int:pk>/delete_comment/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('<int:pk>/delete/', QuestionDeleteView.as_view(), name='question-delete'),
    path('about/', views.about, name='devox-about'),
    # path('<int:pk>/comment/', Comm.as_view(), name='question-comment'),


   # path('create_new/', views.create_quiz, name='question-create'),
    path('(?P<quiz_id>[0-9]+)/', views.detail, name='question-detail'),
   # path('(?P<quiz_id>[0-9]+)/comment/', views.detail, name='question-comment'),
   # path('(?P<quiz_id>[0-9]+)/delete/', views.delete, name='question-delete'),
]

quiz/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    image = models.ImageField(blank=True)
    created = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('quiz:question-detail', args=[str(self.pk)])


class Comment(models.Model):
    comment = models.TextField()
    # image = models.ImageField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment

quiz/forms.py
from django import forms
from .models import Comment, Question


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'content', 'image']

quiz/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from .models import Question, Comment
from .forms import CommentForm, QuestionForm


class QuestionListView(LoginRequiredMixin, ListView):
    model = Question
    template_name = 'quiz/index.html'
    context_object_name = 'questions'
    ordering = ['-created']
    paginate_by = 2


class UserQuestionListView(ListView):
    model = Question
    template_name = 'quiz/user_questions.html'
    context_object_name = 'questions'
    paginate_by = 7

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Question.objects.filter(author=user).order_by('-created')


class QuestionDetailView(DetailView):
    model = Question


class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    fields = ['title', 'content', 'image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class QuestionUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Question

    fields = ['title', 'content', 'image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class QuestionDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Question
    success_url = '/home'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


"""
class CommentListView(ListView):
    model = Comment
    context_object_name = 'comments'
    template_name = ''


class CommentCreateView(CreateView):
    model = Comment
    fields = ['comment']

    def get_success_url(self):
        return reverse('quiz:question-detail', kwargs={'pk': self.get_object(Question.objects.all()).pk})

        pass

    def form_valid(self, form, **kwargs):
        question = get_object_or_404(Question, pk=self.kwargs.get('pk'))
        form.instance.author = self.request.user
        form.instance.question = question
        return super(CommentCreateView, self).form_valid(form)


def detail(request, quiz_id):
    quiz = get_object_or_404(Question, pk=quiz_id)
    return render(request, 'quiz/question_detail.html', {'quiz': quiz})
  
  
def create_quiz(request):
    form = QuestionForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        question = form.save(commit=False)
        question.author = request.user
        question.image = request.FILES['image']
        question.save()
    return render(request, 'quiz/question_form.html', {'form': form})
    
"""


def detail(request, quiz_id):
    form = CommentForm(request.POST or None, request.FILES or None)
    quiz = get_object_or_404(Question, pk=quiz_id)
    if form.is_valid():
        comm = form.save(commit=False)
        comm.author = request.user
        # comm.image = request.FILES['image']
        comm.question = quiz
        comm.save()
    form = CommentForm()
    return render(request, 'quiz/question_detail.html', {'form': form, 'quiz': quiz})


def delete(request, quiz_id):
    quiz = get_object_or_404(Question, pk=quiz_id)
    quiz.delete()
    return redirect('quiz:quiz-index')


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment

    fields = ['comment', 'image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.author:
            return True
        return False


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.author:
            return True
        return False


def about(request):
    return render(request, 'quiz/about.html')


"""
def delete_comment(request, quiz_id, comment_id):
    quiz = get_object_or_404(Question, pk=quiz_id)
    comment = Comment.objects.get(pk=comment_id)
    comment.delete()
    return render(request, 'quiz/question_detail.html', {'quiz': quiz})
    """

quiz/templates/quiz/about.html
{% extends 'quiz/base.html' %}

{% block title %}<title>About</title>{% endblock %}
{% block body %}
<h1>Devox About</h1>
{% endblock %}

quiz/templates/quiz/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/css/main.css' %}">
    {% block title %}<title></title>{% endblock %}
</head>
<body>

<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand mr-4" href="{% url 'quiz:devs-home' %}">Devox</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'quiz:quiz-index' %}">Questions</a>

            </div>

                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'quiz:question-create' %}">New Question</a>


            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ request.user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'user-profile' %}">Profile</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>

            </li>
          </ul>

                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Sign Up</a>
                    {% endif %}
                </div>

            </div>
        </div>
    </nav>
</header>

<main role="main" class="container-fluid">
    <div class="row">
           <div class="col-md-12">
           {% if messages %}
               {% for message in messages %}
                   <div class="alert alert-{{ message.tags }}">
                   {{ message }}
                   </div>
               {% endfor %}
           {% endif %}

            {% block body %}

            {% endblock %}

        </div>


    </div>
    </div>
</main>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

quiz/templates/quiz/comment_form.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Comment</title>{% endblock %}

{% block body %}
<div class="content-section">
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Comment</legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Submit</button>
        <button type="reset" class="btn btn-outline-danger">Cancel</button>
    </div>
</form>

</div>
{% endblock %}

quiz/templates/quiz/home.html
{% extends 'quiz/base.html' %}
{%  load static %}

{% block title %}<title>Devox</title>{% endblock %}
{% block body %}

{% endblock %}

quiz/templates/quiz/index.html
{% extends 'quiz/base.html' %}

{% block title %}<title>Devs Hood</title>{% endblock %}

{% block body %}
{% if questions %}
    <div class="col-sm-8 content-section">
    <div class="alert alert-info"><h5 class="text text-center">Questions:</h5></div>
    {% for quiz in questions %}
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ quiz.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'quiz:user-questions' quiz.author.username %}">{{ quiz.author }}</a>
              <small class="text-muted">{{ quiz.created|date:"F d, Y" }}</small>
            </div>
            <h5><a class="article-title" href="{% url 'quiz:question-detail' quiz.id %}">{{ quiz.pk }}. {{ quiz.title }}</a></h5>
              {% if quiz.image %}

                  <a href="{% url 'quiz:question-detail' quiz.id %}">
                  <img class="img img-thumbnail" style="height: 500px; width: 700px ;" src="{{ quiz.image.url }}">
                  </a>
              {% endif %}
          </div>
        </article>

    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="{{ page_obj.previous_page_number }}">Prev</a>
            {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="{{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        {% endif %}

    {% else %}
 <div class="alert alert-info"><h4 class="text text-center">No Questions:</h4></div>
{% endif %}
</div>

{% endblock %}

quiz/templates/quiz/question_confirm_delete.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Delete {{ object.id }}</title>{% endblock %}

{% block body %}
<div class="content-section">
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4 text-danger">Delete Question</legend>
        <h3>Are you sure you want to delete this question "{{ object.title }}"?</h3>
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-danger">Yes, Delete</button>
        <a href="{% url 'quiz:question-detail' object.id %}" class="btn btn-outline-primary">Cancel</a>
    </div>
</form>

</div>
{% endblock %}

quiz/templates/quiz/question_detail.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Question: {{ quiz.pk }}</title>{% endblock %}

{% block body %}
    <div class="col-sm-6 content-section">
        <article class="">
        <img class="rounded-circle article-img" style="margin: 2px;" src="{{ quiz.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="" style="margin: 2px;" href="{% url 'user-profile' %}">{{ quiz.author }}</a>
              <small class="text-muted">{{ quiz.created|date:"F d, Y" }}</small>
                {% if quiz.author == user %}
                    <div class="">
                    <a class="btn btn-secondary btn-sn mt-1 mb-1" style="margin: 2px;" href="{% url 'quiz:question-update' pk=quiz.pk %}">Update</a>
                    <a class="btn btn-danger btn-sn mt-1 mb-1" style="margin: 2px;" href="{% url 'quiz:question-delete' quiz.id %}">Delete</a>
                    </div>
                {% endif %}
            </div>

            <h5 class="article-title" style="margin: 2px;">{{ quiz.title }}</h5>
            <p class="article-content" style="margin: 2px;">{{ quiz.content }}</p>

          {% if quiz.comment_set %}
              <div class="article-metadata">
              <br>
              <h5 class="text-primary text-outline-info" style="margin: 2px;">Comments: {{ quiz.comment_set.count }}</h5>
          </div>
              {% for i in quiz.comment_set.all %}

                  <p style="margin: 2px;">{{ i.comment }} - <a class="mr-2" href="{% url 'user-profile' %}">{{ i.author }} - {{ i.created|date:"F d, Y" }}</a></p>



                  <hr>

                  <br>

              {% endfor %}

          {% endif %}

    <!-- Trial: Stack Overflow-->
          <br><br>
    <form method="POST" action="{% url 'quiz:question-detail' quiz.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4"><b>Your Comment</b></legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Submit</button>
    </div>
</form>


          </div>


        </article>

    </div>
{% endblock %}

quiz/templates/quiz/question_form.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>New Question</title>{% endblock %}

{% block body %}

<div class="col-sm-6 content-section">
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4 text-primary">New Question</legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Submit</button>
        <button type="reset" class="btn btn-outline-danger">Cancel</button>
    </div>
</form>

</div>
{% endblock %}

quiz/templates/quiz/user_questions.html
{% extends 'quiz/base.html' %}

{% block title %}<title>Devox</title>{% endblock %}

{% block body %}
    <h2 class="mb-3">Post by: {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h2>
{% if questions %}
    {% for quiz in questions %}
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ quiz.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-profile' %}">{{ quiz.author }}</a>
              <small class="text-muted">{{ quiz.created|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'quiz:question-detail' quiz.id %}">{{ quiz.pk }}. {{ quiz.title }}</a></h2>
            <p class="article-content">{{ quiz.content }}</p>
          </div>
        </article>

    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="{{ page_obj.previous_page_number }}">Prev</a>
            {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="{{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        {% endif %}

    {% else %}
    <div class="alert alert-info">
No Questions Yet
</div>
{% endif %}

{% endblock %}