devs_circle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    # Password Reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),


    path('update-profile/', user_views.profile_update, name='update-profile'),
    path('user_profile/', user_views.user_profile, name='user-profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path
from . import views
from .views import (QuestionCreateView, QuestionDetailView,
                    QuestionListView, QuestionUpdateView,
                    QuestionDeleteView, CommentUpdateView, CommentDeleteView,
                    UserQuestionListView)

app_name = 'quiz'

urlpatterns = [
    path('', QuestionListView.as_view(), name='devs-home'),
    path('home/', QuestionListView.as_view(), name='quiz-index'),
    path('user/<str:username>/', UserQuestionListView.as_view(), name='user-questions'),
    # path('<int:pk>/', QuestionDetailView.as_view(), name='question-detail'),
    path('create_new/', QuestionCreateView.as_view(), name='question-create'),
    path('<int:pk>/update/', QuestionUpdateView.as_view(), name='question-update'),
   # path('<int:pk>/comment/', CommentCreateView.as_view(),
    #     name='question-comment'),
    path('<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    # path('<int:pk>/delete_comment/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('<int:pk>/delete/', QuestionDeleteView.as_view(), name='question-delete'),
    path('about/', views.about, name='devox-about'),
    # path('<int:pk>/comment/', Comm.as_view(), name='question-comment'),


   # path('create_new/', views.create_quiz, name='question-create'),
    path('(?P<quiz_id>[0-9]+)/', views.detail, name='question-detail'),
   # path('(?P<quiz_id>[0-9]+)/comment/', views.detail, name='question-comment'),
   # path('(?P<quiz_id>[0-9]+)/delete/', views.delete, name='question-delete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    bio = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, force_insert=False, force_update=False, using=None, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {'username': None}


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image', 'bio']

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from .models import Profile
from quiz.models import Question


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Created for {username}!')
            return redirect('quiz:quiz-index')

    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile_update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your Account Has Been Updated!')
            return redirect('user-profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile_update.html', context)


@login_required
def user_profile(request):
    prof = Profile.objects.get(user=request.user)
    questions = Question.objects.filter(author=request.user)
    return render(request, 'users/user_profile.html', {'prof': prof, 'questions': questions})

users/templates/users/login.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Log in</title>{% endblock %}

{% block body %}
<center>
<div class="col-sm-4 content-section">
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Log in</legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Login</button>
        <small class="text-muted ml-2">Forgot password? <a class="ml-2" href="{% url 'password_reset' %}">Reset</a></small>
    </div>
</form>
<div class="border-top pt-3">
    <small class="text-muted">Don't have an account? <a class="ml-2" href="{% url 'register' %}">Register</a></small>
</div>
</div>
</center>
{% endblock %}

users/templates/users/logout.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Logged out</title>{% endblock %}

{% block body %}
    <center>
<div class="container-fluid">
<div class="col-md-4">
<div class="content-section">
<h2>You've Logged out!</h2>
<div class="border-top pt-3">
    <small class="text-muted"><a class="ml-2" href="{% url 'login' %}">Login Again</a></small>
</div>
</div>
</div>
</div>
    </center>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Password Reset</title>{% endblock %}

{% block body %}
<center>
<div class="container-fluid">
<div class="col-md-4">
<div class="content-section">
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Reset Password</legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Reset Password</button>
        <button type="reset" class="btn btn-outline-danger">Cancel</button>
    </div>
</form>
</div>
</div>
</div>
</center>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Password reser</title>{% endblock %}

{% block body %}
<div class="container">
<div class="alert alert-info">
Your password has been Reset
    <a href="{% url 'login' %}">Login Here</a>
</div>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Password Reset</title>{% endblock %}

{% block body %}
<div class="container">
<div class="col-md-6">
<div class="content-section">
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Reset Password</legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Reset Password</button>
        <button type="reset" class="btn btn-outline-danger">Cancel</button>
    </div>
</form>
</div>
</div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Password reset</title>{% endblock %}

{% block body %}
<div class="container">
<div class="alert alert-info">
    An email has been sent with instructions to reset your password.
</div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>{{ user.username }}</title>{% endblock %}

{% block body %}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
    <div class="media-body">
      <h3 class="account-heading">{{ user.username }}</h3>
      <p class="text-secondary">{{ user.email }}</p>
      <p class="text-secondary">{{ user.profile.bio }}</p>
    </div>
  </div>
  <!-- FORM HERE -->

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Profile Info</legend>
        {{ u_form|crispy }}
        {{ p_form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Update</button>
        <button type="submit" class="btn btn-outline-danger">Cancel</button>
    </div>
</form>

</div>
{% endblock %}

users/templates/users/profile_update.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>{{ user.username }}</title>{% endblock %}

{% block body %}
<div class="col-sm-3 content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
    <div class="media-body">
      <h3 class="account-heading">{{ user.username }}</h3>
      <p class="text-secondary">{{ user.email }}</p>
      <p class="text-secondary">{{ user.profile.bio }}</p>
    </div>
  </div>
  <!-- FORM HERE -->

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4 text-primary">Profile Info</legend>
        {{ u_form|crispy }}
        {{ p_form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Update</button>
        <button type="submit" class="btn btn-outline-danger">Cancel</button>
    </div>
</form>

</div>
{% endblock %}

users/templates/users/register.html
{% extends 'quiz/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Register</title>{% endblock %}

{% block body %}

<center>
<div class="col-md-4">
<div class="content-section">


<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Sign Up</legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Sign Up</button>
    </div>
</form>
<div class="border-top pt-3">
    <small class="text-muted">Already have an account? <a class="ml-2" href="{% url 'login' %}">Login</a></small>
</div>
</div>
</div>
</div>
</center>

{% endblock %}

users/templates/users/user_profile.html
{% extends 'quiz/base.html' %}

{% block title %}<title>{{ user.username }}</title>{% endblock %}

{% block body %}

<div class="content-section">
<div class="row">
<div class="col-sm-3">
    <div class="media">
    <img class="rounded-circle account-img" src="{{ prof.image.url }}">
  </div>
    <p><a href="{% url 'user-profile' %}"> {{ user.username }}</a></p>
        <p>{{ user.email }}</p>
        <p>{{ prof.bio }}</p>
        <p><a class="btn btn-secondary btn-sn mt-1" href="{% url 'update-profile' %}">Update</a></p>
  </div>


       <div class="col-sm-9">
       {% if questions %}
           <div class="alert alert-info"><h4 class="text text-center">My Questions:</h4></div>
            {% for quiz in questions %}
    <h2><a class="article-title" href="{% url 'quiz:question-detail' quiz.id %}">{{ quiz.pk }}. {{ quiz.title }}</a></h2>
        {% if quiz.image %}

                  <a href="{% url 'quiz:question-detail' quiz.id %}">
                  <img class="img img-thumbnail" style="height: 500px; width: 750px ;" src="{{ quiz.image.url }}">
                  </a>
              {% endif %}

        <hr>
       {% endfor %}

       {% else %}
        <div class="alert alert-info"><h4 class="text text-center">No Questions</h4></div>
       </div>
        {% endif %}


</div>
</div>
{% endblock %}